services:
#  backend:
#    image: alexroza/backend-babilonia
#    depends_on:
#      - postgres
#      - keycloak
#    environment:
#      URL_DB: jdbc:postgresql://postgres:5432/postgres
#      USERNAME_DB: alex
#      PASSWORD_DB: alex
#      AUTHORIZATION_SERVE: http://keycloak:8080/realms/master
#      REALM: master
#      CLIENT_ID: spring
#      USERNAME: admin
#      PASSWORD: admin
#      SERVER_URL: http://keycloak:8080/
#    ports:
#      - "8081:8081"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alex
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  keycloak:
    image: keycloak/keycloak
    command:
      - start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
